version: 0.{branch}.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      JAVA_HOME: C:\Program Files\Java\jdk11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      JAVA_HOME: C:\Program Files\Java\jdk13
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      JAVA_HOME: C:\Program Files\Java\jdk15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      JAVA_HOME: C:\Program Files\Java\jdk17
install:
- cmd: SET PATH=%JAVA_HOME%\bin;%PATH%;
build_script:
- cmd: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
- cmd: mvn test -B
notifications:
- provider: Email
  to:
  - slawomir.chodnicki@twineworks.com
  subject: AppVeyor build status
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
cache:
  - '%USERPROFILE%\.m2 -> appveyor.yml'